### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by UserNugget** [SteveTheEngineer/SS-FancyDrops#2]
See video: https://www.youtube.com/watch?v=ZVbQITN8PN4
Item:
 - Buttons
 - Hoes
 - Blaze rod

**Comment by SteveTheEngineer** [comment]
~Looks like that's a problem with your configuration, please attach your config.yml~

**Comment by SteveTheEngineer** [comment]
That was a problem with default config.yml, I've completely forgot to include buttons and hoes in the default config.yml, and typed a character in BLAZE_ROD in lower case.
Please delete your config.yml and update to the latest version (2.0.3): https://www.spigotmc.org/resources/steves-series-fancy-drops.68373/
