### ISSUE TITLE
customName "only looking" & minAmount BUG

### ISSUE THREAD

**Issue by pintoso** [SteveTheEngineer/SS-FancyDrops#6]
1. an option to show "customName" only if you are looking at the item and at a close distance 
it's very useful for players not to be surprised by a lot of strange names behind the wall, and not break the "immersion"

2. [BUG?] the customName/amount is not updating (watch the video)

```
minAmount: 2
maxAmount: 127
```

spigot.yml:
```
merge-radius:
      exp: 4.0
      item: 6.0
```

https://user-images.githubusercontent.com/26844778/107596815-a38db780-6bf7-11eb-9f5e-1a5b04237414.mp4

**Comment by pintoso** [comment]
(maybe) **I got it wrong how minAmount works**

my suggestion is to create a minAmount for customName
for example:
`customName_minAmount: 2`
customName will only appear if the stack is ≥ 2

**Comment by SteveTheEngineer** [comment]
> (maybe) **I got it wrong how minAmount works**
> 
> my suggestion is to create a minAmount for customName
> for example:
> `customName_minAmount: 2`
> customName will only appear if the stack is ≥ 2

For this purpose I'd recommend having two different item presets, one with a custom name, one without. And I'll work on your first suggestion once I have time

**Comment by pintoso** [comment]
thanks for the recommendation, it worked!
but having to "duplicate" all of the presets and edit is a bit boring, but yeah... it worked ^^
>idk if doing it that way can impact performance(?)

**Comment by SteveTheEngineer** [comment]
> thanks for the recommendation, it worked!
> but having to "duplicate" all of the presets and edit is a bit boring, but yeah... it worked ^^
> 
> > idk if doing it that way can impact performance(?)

No, that doesn't impact performance at all

**Comment by SteveTheEngineer** [comment]
Implemented in build 17. See [the skulls.yml file](https://github.com/SteveTheEngineer/SS-FancyDrops/blob/4988e3f383d8236895ff9dc25ae15b6553d63f41/src/main/resources/presets/skulls.yml#L38) to find out how to use it yourself. Or just copy it from the default configuration

**Comment by SteveTheEngineer** [comment]
Also next time please open multiple issues if you have more than one problem, don't merge them into one
