### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by Athamex** [SteveTheEngineer/SS-FancyDrops#8]
can you add support for 1.17 ?

**Comment by SteveTheEngineer** [comment]
The plugin should already work on 1.17. The only thing that needs updating is the default configuration, and you can easily do that by yourself.

**Comment by SteveTheEngineer** [comment]
Note: I am soon going to update this plugin, so 1.18 support is coming.

**Comment by SteveTheEngineer** [comment]
The plugin has been updated to 1.18.2. Closed.
