### ISSUE TITLE
Add support for Item Holograms

### ISSUE THREAD

**Issue by Swirren** [SteveTheEngineer/SS-FancyDrops#9]
More info instead of the item stack amount would be great

https://www.spigotmc.org/resources/%E2%9C%85-item-holograms-1-16-1-19-%E2%9C%85-item-remover-time-to-delete-stops-server-lag-and-more.95577/

**Comment by SteveTheEngineer** [comment]
More clarification on this feature request would be very welcome.

**Comment by Swirren** [comment]
ItemHolograms currently allows a few things - but primarily, a timer for how long is remaining until the item despawns
![image](https://user-images.githubusercontent.com/64167426/212676293-f4a66414-a529-4121-b305-407e5e4e9a66.png)

**Comment by Swirren** [comment]
If you are able to add this functionality in the plugin itself, please do that instead

**Comment by SteveTheEngineer** [comment]
So why not just use that plugin?

**Comment by Swirren** [comment]
The hologram from Fancy Drops overrides Item Holograms

**Comment by Swirren** [comment]
![image](https://user-images.githubusercontent.com/64167426/212677349-214e6caf-474e-4405-82c0-fc3b6eae9018.png)

**Comment by SteveTheEngineer** [comment]
Well, it seems that Item Holograms changes the custom name of the item itself, and the item is not visible with Fancy Drops. So, maybe I could add an option to mirror the custom name of the item entity for this? For now, do you know that you can change those holograms (they're called hints) to whatever you want in presets?

**Comment by Swirren** [comment]
I did see that - but I don't think it can include the custom despawn timer, right? 
Either way, custom name support would be great! Thanks

**Comment by SteveTheEngineer** [comment]
No, it doesn't support despawn timers, never thought of it really. Expect a new build in an hour or so.

**Comment by Swirren** [comment]
I see the build. I'll test it out!

**Comment by SteveTheEngineer** [comment]
Sure. You've noticed rather quickly.

**Comment by Swirren** [comment]
![image](https://user-images.githubusercontent.com/64167426/212686047-26e6b22a-fbe5-440d-8f61-f473ee478217.png)
Unfortunately, it seems like it doesn't work still. I also just noticed a Kotlin conflict error that I could make another issue report for

**Comment by SteveTheEngineer** [comment]
Did you change `customName: x$$amount$$` to `customName: $$customName$$` in `presets/basicItemsStackable.yml`?

**Comment by Swirren** [comment]
Awesome, it works. Only thing I've noticed is that you have to be looking directly at the item for it to display the hologram.
Also, is it possible to add a way for dropped items to not despawn? I've seen it in other servers but I'm not sure what to look for

**Comment by Swirren** [comment]
Left a review on Spigot btw :D

**Comment by Swirren** [comment]
Also this is probably a client sided rendering thing but wanted to mention it: If you look around at certain angles the item disappears 
![image](https://user-images.githubusercontent.com/64167426/212692649-e4ca84e3-870d-43cf-b84b-d8c60b926420.png)
![image](https://user-images.githubusercontent.com/64167426/212692656-f047597f-713f-42fd-b2e1-0d64b230fa3a.png)

**Comment by SteveTheEngineer** [comment]
> Also this is probably a client sided rendering thing but wanted to mention it: If you look around at certain angles the item disappears ![image](https://user-images.githubusercontent.com/64167426/212692649-e4ca84e3-870d-43cf-b84b-d8c60b926420.png) ![image](https://user-images.githubusercontent.com/64167426/212692656-f047597f-713f-42fd-b2e1-0d64b230fa3a.png)

Well, that's true, there's nothing I can do about that.

> Awesome, it works. Only thing I've noticed is that you have to be looking directly at the item for it to display the hologram. Also, is it possible to add a way for dropped items to not despawn? I've seen it in other servers but I'm not sure what to look for

Remove the `customNameBoundingBox` section or whatever it is called and it will be visible regardless. There is most likely already a plugin that stops items from despawning, but even if there isn't, my plugin is only supposed to change how the items look.

And if you don't have any more questions/issues with holograms, please close the issue.

**Comment by Swirren** [comment]
Thanks for the fix and help! If you can also fix the issue with the Kotlin plugin I would like to donate
